def print_help():
    print 'Type in any expressions or assignment statements you want.'
    print 'For example:'
    print '>>  a = 1 + 1'
    print '2'
    print '>>  a = a + pow(2, 2)'
    print '6'
    print '\nYou can also define your own functions, in the form'
    print 'def <function name>([zero or more comma separated args]) = <expression>'
    print '\nFor example,'
    print '>>  def f(x, y) = x * y + 3'
    print '>>  f(2, 3)'
    print '9\n'
    print 'Type "print" to see all values and defined functions.'
    print 'Type "help" to see this message.'